;;; packages.lisp — Package definitions (auto-generated)

(defpackage "BARK"
  (:use "COMMON-LISP")
  (:shadow "DEBUG" "ERROR" "TRACE" "WARN")
  (:export "*COMPILE-TIME-MAX-LEVEL*"
           "*LOG-CONTEXT*"
           "*LOGGER*"
           "*MAX-EMIT-DEPTH*"
           "*MAX-EMIT-LENGTH*"
           ;; Serialization API
           "EMIT-JSON-VALUE" "EMIT-JSON-KEY" "EMIT-JSON-FIELDS"
           "EMIT-LOGFMT-VALUE" "EMIT-LOGFMT-KEY"
           "WRITE-JSON-ESCAPED-STRING" "SERIALIZE-BINDINGS"
           "ASYNC-OUTPUT"
           "CHILD"
           "DEBUG"
           "DESTINATION"
           "ERROR"
           "FATAL"
           "FORMATTER-GROUP"
           "INFO"
           "JSON-FORMATTER"
           "LOG-DEBUG"
           "LOG-ERROR"
           "LOG-FATAL"
           "LOG-INFO"
           "LOG-TRACE"
           "LOG-WARN"
           "LOGFMT-FORMATTER"
           "LOGGER"
           "MAKE-LOGGER"
           "MAKE-TEE"
           "PRETTY-FORMATTER"
           "SET-LEVEL"
           "SET-SAMPLING"
           "START"
           "STOP"
           "TEE-OUTPUT"
           "TRACE"
           "WARN"
           "WITH-CAPTURED-LOGS"
           "WITH-CONTEXT"))
