;;; packages.lisp — Package definitions

(defpackage "BARK"
  (:use "COMMON-LISP")
  (:shadow "DEBUG" "ERROR" "TRACE" "WARN")
  (:export "+DEBUG+" "+ERROR+" "+FATAL+" "+INFO+" "+TRACE+" "+WARN+"
           "+LEVEL-STEP+" "+LEVEL-SLOT-COUNT+"
           "+MIN-RING-CAPACITY+" "+DEFAULT-BUFFER-CAPACITY+"
           "*COMPILE-TIME-MAX-LEVEL*"
           "*LOG-CONTEXT*"
           "*LOGGER*"
           "*MAX-JSON-DEPTH*"
           "*MAX-JSON-LENGTH*"
           "*MAX-PRETTY-DEPTH*"
           "*MAX-PRETTY-LENGTH*"
           ;; Serialization API
           "EMIT-JSON-VALUE" "EMIT-JSON-KEY" "EMIT-JSON-FIELDS"
           "EMIT-LOGFMT-VALUE" "EMIT-LOGFMT-KEY"
           "WRITE-JSON-ESCAPED-STRING" "SERIALIZE-BINDINGS"
           ;; Condition serialization
           "CAPTURE"
           "CAPTURED-ERROR" "CAPTURED-ERROR-P"
           "CAPTURED-ERROR-CONDITION" "CAPTURED-ERROR-STACK"
           "*MAX-JSON-STACK-FRAMES*"
           "*MAX-PRETTY-STACK-FRAMES*"
           "ASYNC-OUTPUT"
           "COMPOSE-FIELD-TRANSFORMS"
           "DEBUG"
           "ERROR"
           "FATAL"
           "INFO"
           "JSON-FORMATTER"
           "LOGGER"
           "LOGGER-P"
           "LOGFMT-FORMATTER"
           ;; Multi-output
           "MAKE-TEE"
           "TEE"
           "MAKE-JSON-FORMATTER"
           "MAKE-CHILD"
           "MAKE-LOGGER"
           "MAKE-LOGFMT-FORMATTER"
           "MAKE-PRETTY-FORMATTER"
           "PRETTY-FORMATTER"
           "SET-LEVEL"
           ;; Sampling — windowed counter
           "MAKE-WINDOWED-COUNTER"
           "MAKE-LEVEL-SAMPLER"
           "SET-LEVEL-SAMPLING"
           "WINDOWED-COUNTER-INITIAL"
           "WINDOWED-COUNTER-THEREAFTER"
           "WINDOWED-COUNTER-WINDOW-TICKS"
           ;; Sampling — consistent
           "MAKE-CONSISTENT-SAMPLER"
           "SET-CONSISTENT"
           "CONSISTENT-SAMPLER-KEY-FN"
           "CONSISTENT-SAMPLER-RATE"
           "FLUSH"
           "STOP"
           "TRACE"
           "WARN"
           "WITH-CAPTURED-LOGS"
           "WITH-CONTEXT"
           "WITH-LOG-BUFFER"
           "*ROOT-LOGGER*"
           "BUFFER-ENTRY" "BUFFER-ENTRY-LEVEL" "BUFFER-ENTRY-MESSAGE"
           "BUFFER-ENTRY-FIELDS" "BUFFER-ENTRY-CONTEXT" "BUFFER-ENTRY-TIMESTAMP"
           "MAKE-BUFFER-ENTRY"
           "CURRENT-LOG-TIMESTAMP-MS"))
