;;; packages.lisp — Package definitions (auto-generated)

(defpackage "BARK"
  (:use "COMMON-LISP")
  (:shadow "DEBUG" "ERROR" "TRACE" "WARN")
  (:export "*COMPILE-TIME-MAX-LEVEL*"
           "*LOG-CONTEXT*"
           "*LOGGER*"
           "ASYNC-OUTPUT"
           "CHILD"
           "DEBUG"
           "ERROR"
           "FATAL"
           "INFO"
           "JSON-FORMATTER"
           "LOG-DEBUG"
           "LOG-ERROR"
           "LOG-FATAL"
           "LOG-INFO"
           "LOG-TRACE"
           "LOG-WARN"
           "LOGFMT-FORMATTER"
           "LOGGER"
           "MAKE-LOGGER"
           "PRETTY-FORMATTER"
           "SET-LEVEL"
           "SET-SAMPLING"
           "START"
           "STOP"
           "TRACE"
           "WARN"
           "WITH-CAPTURED-LOGS"
           "WITH-CONTEXT"))
